### ISSUE TITLE
Possible extension: ignore accents

### ISSUE THREAD

**Issue by tristanvandevelde** [DerDemystifier/SmarterTypeField#2]
Request to extend the current project to not only ignore cases, but also accents in the text. Especially useful when learning stressed languagedssuch as slavic languaes. 
Text of the field with which needs to be compared can be easily modified by the following snippet:

`	
ru_raw = ru_stress.normalize("NFD").replace(/[\u0300-\u036f]/g, '');
`

EDIT: if not interesting to the general public that uses this add on, I will fork and adapt accordingly myself (when permitted).

**Comment by DerDemystifier** [comment]
Good idea! I might add this as an optional feature since accents in some languages are important to learn as well.

You can always fork the project and modify it to your liking. No problem.

**Comment by knakamura8** [comment]
This would be helpful!

**Comment by DerDemystifier** [comment]
After nearly 2 years, I have finally got around to updating the addon to include this (as well as the option to ignore punctuations). 
If you're still interested, you can test use [the updated version](https://ankiweb.net/shared/info/1371444066), or you can keep using your own forked version if you want 😉.
